from sentence_transformers import CrossEncoder
import os

class CrossEncoderProcessor:
    def __init__(self, model_name="cross-encoder/ms-marco-MiniLM-L-6-v2"):
        self.model_name = model_name
        self.local_model_path = os.path.join("local_models", model_name.replace("/", "_"))
        
        # Check if model exists locally, if not download it
        if not os.path.exists(self.local_model_path):
            os.makedirs(self.local_model_path, exist_ok=True)
            self.model = CrossEncoder(model_name)
            self.model.save(self.local_model_path)
        else:
            self.model = CrossEncoder(self.local_model_path)
    
    def cross_encode(self, query, passages):
        """
        Perform cross encoding between a query and a list of passages
        
        Args:
            query (str): The query text
            passages (list): List of passages to compare with query
            
        Returns:
            list: List of similarity scores
        """
        pairs = [[query, passage] for passage in passages]
        scores = self.model.predict(pairs)
        return scores

processor = CrossEncoderProcessor()

def cross_encode_sort(query: str, passages: list, n_results: int = 5):
    """
    Perform cross encoding between a query and a list of passages and sort them in descending order
    
    Args:
        query (str): The query text
        passages (list): List of passages to compare with query
        n_results (int): Number of results to return
    
    Returns:
        list: List of similarity scores
    """
    scores = processor.cross_encode(query, passages)
    sorted_passages = sorted(zip(passages, scores), key=lambda x: x[1], reverse=True)
    passages = [p for p, _ in sorted_passages]
    
    return passages[:n_results]

if __name__ == "__main__":
    processor = CrossEncoderProcessor()
    query = "yo'l xaritasi"
    passages = [
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 20. Yillik statistika hisobotini taqdim etishdan ozod etiladigan korxonalar ro‘yxatini shakllantirish. Amalga oshirish mexanizmi: 1) Kichik tadbirkorlik subyektlarining ro‘yxatini, shu jumladan, xodimlar soni va yillik mahsulot (tovar, ish va xizmatlar) sotishdan tushgan sof tushumi, aksiz solig‘ini to‘lovchilar ro‘yxati haqidagi ma’lumotlarni statistika organlariga taqdim etib borish. 2) Davlat ulushi 50 foiz va undan yuqori bo‘lgan korxonalar ro‘yxatini statistika organlariga taqdim etish. Amalga oshirish muddati: 11 oylik ma’lumotlar kelgusi yilning 1-fevraliga qadar, yillik ma’lumotlar kelgusi yilning 5-martiga qadar, 1-fevraliga qadar. Mas’ul organ: Soliq qo‘mitasi, Davlat aktivlarini boshqarish agentligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 9. Kuzatilmaydigan iqtisodiyotni baholash natijalari asosida yalpi ichki mahsulotning tarmoq va hududlar kesimidagi dinamika qatorlarini shakllantirish. Amalga oshirish mexanizmi: 1) Kuzatilmaydigan iqtisodiyotni baholash bo‘yicha metodik yondashuvlardagi o‘zgarishlarni inobatga olgan holda 2010 — 2017-yillar uchun YAIMning tarmoq va hududlar kesimidagi dinamika qatorlarini shakllantirish 2) Amalga oshirilgan hisob-kitoblar natijalarini Xalqaro valyuta jamg‘armasi eksperti bilan muhokama qilish. 3) Kuzatilmaydigan iqtisodiyotni baholash natijalarini hisobga olgan holda yalpi ichki mahsulotning tarmoq va hududlar kesimidagi dinamika qatorlarini e’lon qilish. Amalga oshirish muddati: 2025-yil sentabr, Mas’ul organ: Milliy statistika qo‘mitasi,",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 31. Xalqaro valyuta jamg‘armasining (XVJ) axborot tizimlarida mamlakatning asosiy makroiqtisodiy va moliyaviy ko‘rsatkichlarini aks ettirishni ta’minlash. Amalga oshirish mexanizmi: 1) Xalqaro valyuta jamg‘armasining Kengaytirilgan ma’lumotlarni tarqatishning umumiy tizimi (k-MTUT)dan Ma’lumotlarni tarqatishning maxsus tizimi (MTMT)ga o‘tish. 2) Xalqaro valyuta jamg‘armasining Xalqaro moliya statistikasi sahifasida talab etiladigan asosiy makroiqtisodiy, moliyaviy va ijtimoiy statistika ko‘rsatkichlarining e’lon qilib borilishini ta’minlash. Amalga oshirish muddati: 2025-yil dekabr, Doimiy. Mas’ul organ: Iqtisodiyot va moliya vazirligi, Milliy statistika qo‘mitasi, Markaziy bank",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 27. Koreya statistika idorasi (Statistics Korea) bilan grant loyihani amalga oshirish. Amalga oshirish mexanizmi: 1) Koreya statistika idorasi (Statistics Korea) bilan Milliy statistika qo‘mitasining statistik salohiyatini mustahkamlash bo‘yicha 2025 — 2028-yillarda amalga oshirilishi rejalashtirilgan Koreya hukumati granti loyihasini boshlash uchun tegishli choralar ko‘rish. Amalga oshirish muddati: 2025-yil dekabr. Mas’ul organ: Milliy statistika qo‘mitasi, Investitsiyalar, sanoat va savdo vazirligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 14. Maxsus iqtisodiy zonalar, kichik sanoat zonalari hamda yoshlar sanoat zonalari tarkibiga kiruvchi tadbirkorlik subyektlari haqidagi ma’lumotlarning yuritilishini ta’minlash. Amalga oshirish mexanizmi: 1)Maxsus iqtisodiy zonalar, kichik sanoat zonalari hamda yoshlar sanoat zonalari tarkibiga kiruvchi tadbirkorlik subyektlari haqidagi ma’lumotlarni (a’zolik haqidagi guvohnoma raqami, iqtisodiy zona nomi va undagi korxonalar ro‘yxati, STIR raqami, loyiha qiymati, ish o‘rinlari va boshqalar) yuritishga ixtisoslashgan elektron platformani ishlab chiqish. 2) Mazkur platformani Milliy statistika qo‘mitasining axborot tizimiga integratsiya qilish. Amalga oshirish muddati: 2025-yil sentabr, 2025-yil dekabr, Mas’ul organ: Investitsiyalar, sanoat va savdo vazirligi, Milliy statistika qo‘mitasi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Boshqa yo‘nalishlarda. 36. Mavjud resurslardan foydalangan holda statistika organlarining moddiy-texnika bazasini mustahkamlash. Amalga oshirish mexanizmi: 1) Hududiy statistika organlari balansidagi tuman (shahar) bo‘limlari binolarini belgilangan tartibda sotish choralarini ko‘rish hamda sotishdan tushgan mablag‘larni statistika organlari moddiy-texnika bazasini mustahkamlashga yo‘naltirish. 2) Hududiy statistika organlarini joylashtirish uchun tuman va shahar hokimliklari binosidan zarur xonalarni ajratish hamda ijara qiymatini “nol” stavkada belgilash. Amalga oshirish muddati: 2025-yil davomida, Doimiy. Mas’ul organ: Milliy statistika qo‘mitasi, Iqtisodiyot va moliya vazirligi, Davlat aktivlarini boshqarish agentligi, oraqalpog‘iston Respublikasi Vazirlar Kengashi, viloyatlar va Toshkent shahar hokimliklari",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Ochiq ma’lumotlar portalini takomillashtirish yo‘nalishida. 33. Ochiq ma’lumotlar portali faoliyatida geofazoviy ma’lumotlarni joylashtirish. Amalga oshirish mexanizmi: 1) Ochiq ma’lumotlar portalida geofazoviy ma’lumotlarni joylashtirish funksiyasini xalqaro tajribani o‘rgangan holda yanada takomillashtirish. 2) Ochiq ma’lumotlar portalida ma’lumotlarni joylashtiruvchi davlat organlari va tashkilotlari mas’ul xodimlarining xalqaro tajriba asosida geofazoviy ma’lumotlarni shakllantirish bo‘yicha malakasini oshirish. 3) Ochiq ma’lumotlar portalida geofazoviy ma’lumotlar sonini oshirish bo‘yicha choralarni ko‘rish. Amalga oshirish muddati: 2025-yil sentabr, 2025-yil noyabr, 2025-yil dekabr. Mas’ul organ: Raqamli texnologiyalar vazirligi, Milliy statistika qo‘mitasi, tegishli vazirlik va idoralar",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”da 1. Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida. 2. Tarmoqlar statistikasini takomillashtirish yo‘nalishida. 3. Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 4. Ochiq ma’lumotlar portalini takomillashtirish yo‘nalishida. 5. Boshqa yo‘nalishlarda chora-tadbirlar va uning amalga oshirish mexanizmlari, amalga oshirish muddati hamda Mas’ul organ ko'rsdatilgan.",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida 1. Statistik hisobotlarni to‘ldirish jarayonida real vaqt rejimida maslahatlar beruvchi beradigan sun’iy intellekt texnologiyalariga asoslangan chat-bot AI ishlab chiqish. Amalga oshirish mexanizmi: 1) Sun’iy intellekt texnologiyalarini statistik hisobotlarni qabul qilish jarayonlariga joriy etish bo‘yicha xalqaro tajribani o‘rganish. 2) Statistika hisobotlarini onlayn tarzda taqdim etishning e-Stat 4.0 axborot tizimi uchun sun’iy intellekt (artificial intelligence) texnologiyasi asosida “Maslahatchi” interaktiv xizmati (chat-bot) modulini ishlab chiqish. Amalga oshirish muddati: 2025-yil sentabr, 2026-yil yanvar, Mas’ul organ: Milliy statistika qo‘mitasi, Raqamli texnologiyalar vazirligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 28. Xalqaro qo‘llanma, tavsiya va standartlar elektron bazasini yaratish. Amalga oshirish mexanizmi: 1) Xalqaro tashkilotlar tomonidan ishlab chiqilgan xalqaro statistika qo‘llanmalari, tavsiyalari va standartlari elektron bazasini yaratish va uslubiy materiallar kutubxonasiga (https://lib.stat.uz) joylashtirish. Amalga oshirish muddati: 2025-yil oktabr. Mas’ul organ: Milliy statistika qo‘mitasi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Ochiq ma’lumotlar portalini takomillashtirish yo‘nalishida. 34. Ochiq ma’lumotlar sohasidagi “Open Data Inventory” va “Gender Data Compass” xalqaro reytinglarda O‘zbekiston o‘rnini yaxshilash. Amalga oshirish mexanizmi: 1) Ochiq ma’lumotlar sohasidagi “Open Data Inventory” va “Gender Data Compass” xalqaro reytinglarining yangilangan baholash tizimini o‘rganish. 2) “Open Data Inventory” va “Gender Data Compass” xalqaro reytinglarining yangilangan baholash tizimi asosida Ochiq ma’lumotlar portalida va Milliy statistika qo‘mitasining “SIAT” axborot tizimida ma’lumotlarni joylashtirish. 3) Ochiq ma’lumotlar portalida va Milliy statistika qo‘mitasining “SIAT” axborot tizimida joylashtirilgan ma’lumotlarni “Open Data Inventory” va “Gender Data Compass” reytinglarini yuritadigan “Open Data Watch” xalqaro tashkilotiga taqdim etish. Amalga oshirish muddati: 2025-yil may, 2025-yil noyabr, 2025-yil dekabr. Mas’ul organ: Milliy statistika qo‘mitasi, tegishli vazirlik va idoralar",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 12. Ko‘p o‘lchovli kambag‘allikni baholab borishni joriy qilish. Amalga oshirish mexanizmi: 1) Xalqaro ekspertlar ishtirokida turli toifadagi aholi qatlami qamrovini ta’minlash maqsadida ko‘p o‘lchovli kambag‘allikni baholab borish uslubiyotini ishlab chiqish. 2) Uy xo‘jaliklari tanlanma kuzatuvlari ma’lumotlari asosida ko‘p o‘lchovli kambag‘allik darajasini tajriba-sinov tariqasida hisoblashni yo‘lga qo‘yish. Amalga oshirish muddati: 2025-yil dekabr, 2026-yil iyun, Mas’ul organ: Milliy statistika qo‘mitasi, Ijtimoiy himoya milliy agentligi, Kambag‘allikni qisqartirish va bandlik vazirligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 32. Iqtisodiy, investitsiya va energetika komplekslarida amalga oshirilayotgan loyihalar natijadorligini baholash ko‘rsatkichlarini shakllantirish. Amalga oshirish mexanizmi: 1) Iqtisodiy, investitsiya va energetika komplekslarida amalga oshirilayotgan loyihalar natijadorligini baholash ko‘rsatkichlari va ularni shakllantirish tartibi loyihasini ishlab chiqish. Amalga oshirish muddati: 2025-yil iyun. Mas’ul organ: Iqtisodiyot va moliya vazirligi, Investitsiyalar, sanoat va savdo vazirligi, Milliy statistika qo‘mitasi, tegishli vazirlik va idoralar",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida 7. Statistik kuzatuvlarni o‘tkazish jarayonlariga telefon aloqasi yordamida intervyu o‘tkazish (CATI — Computer Assisted Telephone Interviewing) imkonini beruvchi call-markaz faoliyatini yo‘lga qo‘yish. Amalga oshirish mexanizmi: 1) Call-markaz faoliyatini autsorsing xizmatidan foydalangan holda tashkil qilish hamda unga oliy ta’lim muassasalarining bitiruvchi kurs talabalarini jalb etish. 2) Milliy statistika qo‘mitasiga uning so‘roviga asosan taqdim etiladigan telefon raqamlar bazalaridan foydalanishga ruxsat berish. Amalga oshirish muddati: 2025-yil 1-sentabrdan boshlab, Mas’ul organ: Milliy statistika qo‘mitasi, Raqamli texnologiyalar vazirligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 29. Milliy statistika qo‘mitasining xalqaro tashkilotlardagi faolligini kengaytirish. Amalga oshirish mexanizmi: 1) Milliy statistika qo‘mitasining xalqaro tashkilotlarda, xususan Osiyo va Tinch okeani mintaqasi uchun BMTning Iqtisodiy va ijtimoiy komissiyasi (ESKATO) Statistika byurosida, Yevropa statistiklar konferensiyasi Byurosida va Islom hamkorlik tashkiloti Statistika qo‘mitasi Byurosida samarali ishtirok etishini ta’minlash. Amalga oshirish muddati: 2025-2026-yillar. Mas’ul organ: Milliy statistika qo‘mitasi, Tashqi ishlar vazirligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 10. “Resurslar va ulardan foydalanish” jadvallarini tuzish amaliyotini takomillashtirish.  Amalga oshirish mexanizmi: 1) Xalqaro valyuta jamg‘armasi eksperti tavsiyalari asosida korxonalar va tashkilotlarning mahsulotlarni ishlab chiqarish va sotish xarajatlari tarkibini kuzatish bo‘yicha so‘rovnoma shaklini ishlab chiqish. 2) Korxona va tashkilotlar tomonidan mahsulot ishlab chiqarish va sotishga yo‘naltirilgan xarajatlar tarkibining bir martalik tanlanma kuzatuvini tashkil etish va o‘tkazish tartibini ishlab chiqish. 3) 2024-yil ma’lumotlari asosida 30 mingdan ortiq korxonalar va tashkilotlarning mahsulotlarni ishlab chiqarish va sotish xarajatlari tarkibini 143 ta iqtisodiy faoliyat turi bo‘yicha kuzatish. 4) O‘tkazilgan kuzatuv natijalari asosida “Xarajatlar-ishlab chiqarish” koeffitsiyentlarini yangilash orqali “Resurslar va ulardan foydalanish” jadvallarini tuzish amaliyotini takomillashtirish. Amalga oshirish muddati: 2025-yil aprel, 2025-yil may, 2025-yil may — iyul, 2026-yil dekabr, Mas’ul organ: Milliy statistika qo‘mitasi,",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 21. Samaradorlik ko‘rsatkichlarining uslubiyotini ishlab chiqish. Amalga oshirish mexanizmi: 1) Energiya samaradorligi ko‘rsatkichlarini, ularning uslubiyotini xalqaro tavsiya va qo‘llanmalar asosida qayta ko‘rib chiqish hamda rasmiy veb-sayt, ijtimoiy tarmoqlar va boshqa axborot resurslarida e’lon qilish. 2) Xalqaro tavsiya va qo‘llanmalar asosida investitsiya samaradorlik ko‘rsatkichini hisoblash uslubiyotini ishlab chiqish va amaliyotga joriy qilish. Amalga oshirish muddati: 2025-2026-yillar, 2025-2026-yillar. Mas’ul organ: Energetika vazirligi, Milliy statistika qo‘mitasi, Investitsiyalar, sanoat va savdo vazirligi, Iqtisodiyot va moliya vazirligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 19. Faoliyat yuritayotgan yuridik shaxs tashkil etmagan tadbirkorlik subyektlarining IFUT xos raqamini axborot tizimlarida qayd etish. Amalga oshirish mexanizmi: 1) Milliy statistika qo‘mitasi tomonidan yuridik shaxs tashkil etmagan tadbirkorlik subyektlarining asosiy va qo‘shimcha faoliyat turi hamda tegishli IFUT xos raqamini belgilagan holda ma’lumotlarni Adliya vazirligiga taqdim etish. 2) Yuridik shaxs tashkil etmagan tadbirkorlik subyektlarini davlat ro‘yxatidan o‘tkazishni ular shug‘ullanishi mumkin bo‘lgan faoliyat turlari hamda Iqtisodiy faoliyat turlarining umumdavlat tasniflagichi asosida amalga oshirish. Amalga oshirish muddati: 2025-yil aprel, 2025-yil iyun. Mas’ul organ: Milliy statistika qo‘mitasi, Adliya vazirligi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida 6. Hududiy boshqarmalarni zamonaviy server qurilmalari bilan ta’minlash. Amalga oshirish mexanizmi: 1) Qo‘shimcha server qurilmalarini xarid qilish bo‘yicha loyiha hujjatlarini tayyorlash. 2) “O‘zbekistonda statistika tizimi salohiyatini mustahkamlash” loyihasi doirasida xarid qilish ishlarini amalga oshirish. 3)Milliy statistika qo‘mitasi tizimida server qurilmalarini foydalanishga joriy etish.  Amalga oshirish muddati: 2025-yil dekabr, Mas’ul organ: Milliy statistika qo‘mitasi",
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 30. Xalqaro mehnat tashkilotiga (XMT) ma’lumotlarni taqdim etish. Amalga oshirish mexanizmi: 1) Xalqaro mehnat tashkiloti talablari asosida “Xalqaro mehnat statistikasi” axborot tizimiga O‘zbekistonda ishchi kuchi kuzatuvlari ma’lumotlarini o‘z muddatida va to‘liq taqdim etib borish. Amalga oshirish muddati: Yilda bir marotaba. Mas’ul organ: Kambag‘allikni qisqartirish va bandlik vazirligi, Milliy statistika qo‘mitasi"
        ]
    natija = [
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”da 1. Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida. 2. Tarmoqlar statistikasini takomillashtirish yo‘nalishida. 3. Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 4. Ochiq ma’lumotlar portalini takomillashtirish yo‘nalishida. 5. Boshqa yo‘nalishlarda chora-tadbirlar va uning amalga oshirish mexanizmlari, amalga oshirish muddati hamda Mas’ul organ ko'rsdatilgan.", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 28. Xalqaro qo‘llanma, tavsiya va standartlar elektron bazasini yaratish. Amalga oshirish mexanizmi: 1) Xalqaro tashkilotlar tomonidan ishlab chiqilgan xalqaro statistika qo‘llanmalari, tavsiyalari va standartlari elektron bazasini yaratish va uslubiy materiallar kutubxonasiga (https://lib.stat.uz) joylashtirish. Amalga oshirish muddati: 2025-yil oktabr. Mas’ul organ: Milliy statistika qo‘mitasi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 32. Iqtisodiy, investitsiya va energetika komplekslarida amalga oshirilayotgan loyihalar natijadorligini baholash ko‘rsatkichlarini shakllantirish. Amalga oshirish mexanizmi: 1) Iqtisodiy, investitsiya va energetika komplekslarida amalga oshirilayotgan loyihalar natijadorligini baholash ko‘rsatkichlari va ularni shakllantirish tartibi loyihasini ishlab chiqish. Amalga oshirish muddati: 2025-yil iyun. Mas’ul organ: Iqtisodiyot va moliya vazirligi, Investitsiyalar, sanoat va savdo vazirligi, Milliy statistika qo‘mitasi, tegishli vazirlik va idoralar", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 27. Koreya statistika idorasi (Statistics Korea) bilan grant loyihani amalga oshirish. Amalga oshirish mexanizmi: 1) Koreya statistika idorasi (Statistics Korea) bilan Milliy statistika qo‘mitasining statistik salohiyatini mustahkamlash bo‘yicha 2025 — 2028-yillarda amalga oshirilishi rejalashtirilgan Koreya hukumati granti loyihasini boshlash uchun tegishli choralar ko‘rish. Amalga oshirish muddati: 2025-yil dekabr. Mas’ul organ: Milliy statistika qo‘mitasi, Investitsiyalar, sanoat va savdo vazirligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida 6. Hududiy boshqarmalarni zamonaviy server qurilmalari bilan ta’minlash. Amalga oshirish mexanizmi: 1) Qo‘shimcha server qurilmalarini xarid qilish bo‘yicha loyiha hujjatlarini tayyorlash. 2) “O‘zbekistonda statistika tizimi salohiyatini mustahkamlash” loyihasi doirasida xarid qilish ishlarini amalga oshirish. 3)Milliy statistika qo‘mitasi tizimida server qurilmalarini foydalanishga joriy etish.  Amalga oshirish muddati: 2025-yil dekabr, Mas’ul organ: Milliy statistika qo‘mitasi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 30. Xalqaro mehnat tashkilotiga (XMT) ma’lumotlarni taqdim etish. Amalga oshirish mexanizmi: 1) Xalqaro mehnat tashkiloti talablari asosida “Xalqaro mehnat statistikasi” axborot tizimiga O‘zbekistonda ishchi kuchi kuzatuvlari ma’lumotlarini o‘z muddatida va to‘liq taqdim etib borish. Amalga oshirish muddati: Yilda bir marotaba. Mas’ul organ: Kambag‘allikni qisqartirish va bandlik vazirligi, Milliy statistika qo‘mitasi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 12. Ko‘p o‘lchovli kambag‘allikni baholab borishni joriy qilish. Amalga oshirish mexanizmi: 1) Xalqaro ekspertlar ishtirokida turli toifadagi aholi qatlami qamrovini ta’minlash maqsadida ko‘p o‘lchovli kambag‘allikni baholab borish uslubiyotini ishlab chiqish. 2) Uy xo‘jaliklari tanlanma kuzatuvlari ma’lumotlari asosida ko‘p o‘lchovli kambag‘allik darajasini tajriba-sinov tariqasida hisoblashni yo‘lga qo‘yish. Amalga oshirish muddati: 2025-yil dekabr, 2026-yil iyun, Mas’ul organ: Milliy statistika qo‘mitasi, Ijtimoiy himoya milliy agentligi, Kambag‘allikni qisqartirish va bandlik vazirligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida 1. Statistik hisobotlarni to‘ldirish jarayonida real vaqt rejimida maslahatlar beruvchi beradigan sun’iy intellekt texnologiyalariga asoslangan chat-bot AI ishlab chiqish. Amalga oshirish mexanizmi: 1) Sun’iy intellekt texnologiyalarini statistik hisobotlarni qabul qilish jarayonlariga joriy etish bo‘yicha xalqaro tajribani o‘rganish. 2) Statistika hisobotlarini onlayn tarzda taqdim etishning e-Stat 4.0 axborot tizimi uchun sun’iy intellekt (artificial intelligence) texnologiyasi asosida “Maslahatchi” interaktiv xizmati (chat-bot) modulini ishlab chiqish. Amalga oshirish muddati: 2025-yil sentabr, 2026-yil yanvar, Mas’ul organ: Milliy statistika qo‘mitasi, Raqamli texnologiyalar vazirligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 29. Milliy statistika qo‘mitasining xalqaro tashkilotlardagi faolligini kengaytirish. Amalga oshirish mexanizmi: 1) Milliy statistika qo‘mitasining xalqaro tashkilotlarda, xususan Osiyo va Tinch okeani mintaqasi uchun BMTning Iqtisodiy va ijtimoiy komissiyasi (ESKATO) Statistika byurosida, Yevropa statistiklar konferensiyasi Byurosida va Islom hamkorlik tashkiloti Statistika qo‘mitasi Byurosida samarali ishtirok etishini ta’minlash. Amalga oshirish muddati: 2025-2026-yillar. Mas’ul organ: Milliy statistika qo‘mitasi, Tashqi ishlar vazirligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 21. Samaradorlik ko‘rsatkichlarining uslubiyotini ishlab chiqish. Amalga oshirish mexanizmi: 1) Energiya samaradorligi ko‘rsatkichlarini, ularning uslubiyotini xalqaro tavsiya va qo‘llanmalar asosida qayta ko‘rib chiqish hamda rasmiy veb-sayt, ijtimoiy tarmoqlar va boshqa axborot resurslarida e’lon qilish. 2) Xalqaro tavsiya va qo‘llanmalar asosida investitsiya samaradorlik ko‘rsatkichini hisoblash uslubiyotini ishlab chiqish va amaliyotga joriy qilish. Amalga oshirish muddati: 2025-2026-yillar, 2025-2026-yillar. Mas’ul organ: Energetika vazirligi, Milliy statistika qo‘mitasi, Investitsiyalar, sanoat va savdo vazirligi, Iqtisodiyot va moliya vazirligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Raqamli texnologiyalardan foydalanishni kengaytirish yo‘nalishida 7. Statistik kuzatuvlarni o‘tkazish jarayonlariga telefon aloqasi yordamida intervyu o‘tkazish (CATI — Computer Assisted Telephone Interviewing) imkonini beruvchi call-markaz faoliyatini yo‘lga qo‘yish. Amalga oshirish mexanizmi: 1) Call-markaz faoliyatini autsorsing xizmatidan foydalangan holda tashkil qilish hamda unga oliy ta’lim muassasalarining bitiruvchi kurs talabalarini jalb etish. 2) Milliy statistika qo‘mitasiga uning so‘roviga asosan taqdim etiladigan telefon raqamlar bazalaridan foydalanishga ruxsat berish. Amalga oshirish muddati: 2025-yil 1-sentabrdan boshlab, Mas’ul organ: Milliy statistika qo‘mitasi, Raqamli texnologiyalar vazirligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 20. Yillik statistika hisobotini taqdim etishdan ozod etiladigan korxonalar ro‘yxatini shakllantirish. Amalga oshirish mexanizmi: 1) Kichik tadbirkorlik subyektlarining ro‘yxatini, shu jumladan, xodimlar soni va yillik mahsulot (tovar, ish va xizmatlar) sotishdan tushgan sof tushumi, aksiz solig‘ini to‘lovchilar ro‘yxati haqidagi ma’lumotlarni statistika organlariga taqdim etib borish. 2) Davlat ulushi 50 foiz va undan yuqori bo‘lgan korxonalar ro‘yxatini statistika organlariga taqdim etish. Amalga oshirish muddati: 11 oylik ma’lumotlar kelgusi yilning 1-fevraliga qadar, yillik ma’lumotlar kelgusi yilning 5-martiga qadar, 1-fevraliga qadar. Mas’ul organ: Soliq qo‘mitasi, Davlat aktivlarini boshqarish agentligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Boshqa yo‘nalishlarda. 36. Mavjud resurslardan foydalangan holda statistika organlarining moddiy-texnika bazasini mustahkamlash. Amalga oshirish mexanizmi: 1) Hududiy statistika organlari balansidagi tuman (shahar) bo‘limlari binolarini belgilangan tartibda sotish choralarini ko‘rish hamda sotishdan tushgan mablag‘larni statistika organlari moddiy-texnika bazasini mustahkamlashga yo‘naltirish. 2) Hududiy statistika organlarini joylashtirish uchun tuman va shahar hokimliklari binosidan zarur xonalarni ajratish hamda ijara qiymatini “nol” stavkada belgilash. Amalga oshirish muddati: 2025-yil davomida, Doimiy. Mas’ul organ: Milliy statistika qo‘mitasi, Iqtisodiyot va moliya vazirligi, Davlat aktivlarini boshqarish agentligi, oraqalpog‘iston Respublikasi Vazirlar Kengashi, viloyatlar va Toshkent shahar hokimliklari", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 9. Kuzatilmaydigan iqtisodiyotni baholash natijalari asosida yalpi ichki mahsulotning tarmoq va hududlar kesimidagi dinamika qatorlarini shakllantirish. Amalga oshirish mexanizmi: 1) Kuzatilmaydigan iqtisodiyotni baholash bo‘yicha metodik yondashuvlardagi o‘zgarishlarni inobatga olgan holda 2010 — 2017-yillar uchun YAIMning tarmoq va hududlar kesimidagi dinamika qatorlarini shakllantirish 2) Amalga oshirilgan hisob-kitoblar natijalarini Xalqaro valyuta jamg‘armasi eksperti bilan muhokama qilish. 3) Kuzatilmaydigan iqtisodiyotni baholash natijalarini hisobga olgan holda yalpi ichki mahsulotning tarmoq va hududlar kesimidagi dinamika qatorlarini e’lon qilish. Amalga oshirish muddati: 2025-yil sentabr, Mas’ul organ: Milliy statistika qo‘mitasi,", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Xalqaro hamkorlikni kengaytirish va mustahkamlash yo‘nalishida. 31. Xalqaro valyuta jamg‘armasining (XVJ) axborot tizimlarida mamlakatning asosiy makroiqtisodiy va moliyaviy ko‘rsatkichlarini aks ettirishni ta’minlash. Amalga oshirish mexanizmi: 1) Xalqaro valyuta jamg‘armasining Kengaytirilgan ma’lumotlarni tarqatishning umumiy tizimi (k-MTUT)dan Ma’lumotlarni tarqatishning maxsus tizimi (MTMT)ga o‘tish. 2) Xalqaro valyuta jamg‘armasining Xalqaro moliya statistikasi sahifasida talab etiladigan asosiy makroiqtisodiy, moliyaviy va ijtimoiy statistika ko‘rsatkichlarining e’lon qilib borilishini ta’minlash. Amalga oshirish muddati: 2025-yil dekabr, Doimiy. Mas’ul organ: Iqtisodiyot va moliya vazirligi, Milliy statistika qo‘mitasi, Markaziy bank", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 19. Faoliyat yuritayotgan yuridik shaxs tashkil etmagan tadbirkorlik subyektlarining IFUT xos raqamini axborot tizimlarida qayd etish. Amalga oshirish mexanizmi: 1) Milliy statistika qo‘mitasi tomonidan yuridik shaxs tashkil etmagan tadbirkorlik subyektlarining asosiy va qo‘shimcha faoliyat turi hamda tegishli IFUT xos raqamini belgilagan holda ma’lumotlarni Adliya vazirligiga taqdim etish. 2) Yuridik shaxs tashkil etmagan tadbirkorlik subyektlarini davlat ro‘yxatidan o‘tkazishni ular shug‘ullanishi mumkin bo‘lgan faoliyat turlari hamda Iqtisodiy faoliyat turlarining umumdavlat tasniflagichi asosida amalga oshirish. Amalga oshirish muddati: 2025-yil aprel, 2025-yil iyun. Mas’ul organ: Milliy statistika qo‘mitasi, Adliya vazirligi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Ochiq ma’lumotlar portalini takomillashtirish yo‘nalishida. 33. Ochiq ma’lumotlar portali faoliyatida geofazoviy ma’lumotlarni joylashtirish. Amalga oshirish mexanizmi: 1) Ochiq ma’lumotlar portalida geofazoviy ma’lumotlarni joylashtirish funksiyasini xalqaro tajribani o‘rgangan holda yanada takomillashtirish. 2) Ochiq ma’lumotlar portalida ma’lumotlarni joylashtiruvchi davlat organlari va tashkilotlari mas’ul xodimlarining xalqaro tajriba asosida geofazoviy ma’lumotlarni shakllantirish bo‘yicha malakasini oshirish. 3) Ochiq ma’lumotlar portalida geofazoviy ma’lumotlar sonini oshirish bo‘yicha choralarni ko‘rish. Amalga oshirish muddati: 2025-yil sentabr, 2025-yil noyabr, 2025-yil dekabr. Mas’ul organ: Raqamli texnologiyalar vazirligi, Milliy statistika qo‘mitasi, tegishli vazirlik va idoralar", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 14. Maxsus iqtisodiy zonalar, kichik sanoat zonalari hamda yoshlar sanoat zonalari tarkibiga kiruvchi tadbirkorlik subyektlari haqidagi ma’lumotlarning yuritilishini ta’minlash. Amalga oshirish mexanizmi: 1)Maxsus iqtisodiy zonalar, kichik sanoat zonalari hamda yoshlar sanoat zonalari tarkibiga kiruvchi tadbirkorlik subyektlari haqidagi ma’lumotlarni (a’zolik haqidagi guvohnoma raqami, iqtisodiy zona nomi va undagi korxonalar ro‘yxati, STIR raqami, loyiha qiymati, ish o‘rinlari va boshqalar) yuritishga ixtisoslashgan elektron platformani ishlab chiqish. 2) Mazkur platformani Milliy statistika qo‘mitasining axborot tizimiga integratsiya qilish. Amalga oshirish muddati: 2025-yil sentabr, 2025-yil dekabr, Mas’ul organ: Investitsiyalar, sanoat va savdo vazirligi, Milliy statistika qo‘mitasi", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Tarmoqlar statistikasini takomillashtirish yo‘nalishida 10. “Resurslar va ulardan foydalanish” jadvallarini tuzish amaliyotini takomillashtirish.  Amalga oshirish mexanizmi: 1) Xalqaro valyuta jamg‘armasi eksperti tavsiyalari asosida korxonalar va tashkilotlarning mahsulotlarni ishlab chiqarish va sotish xarajatlari tarkibini kuzatish bo‘yicha so‘rovnoma shaklini ishlab chiqish. 2) Korxona va tashkilotlar tomonidan mahsulot ishlab chiqarish va sotishga yo‘naltirilgan xarajatlar tarkibining bir martalik tanlanma kuzatuvini tashkil etish va o‘tkazish tartibini ishlab chiqish. 3) 2024-yil ma’lumotlari asosida 30 mingdan ortiq korxonalar va tashkilotlarning mahsulotlarni ishlab chiqarish va sotish xarajatlari tarkibini 143 ta iqtisodiy faoliyat turi bo‘yicha kuzatish. 4) O‘tkazilgan kuzatuv natijalari asosida “Xarajatlar-ishlab chiqarish” koeffitsiyentlarini yangilash orqali “Resurslar va ulardan foydalanish” jadvallarini tuzish amaliyotini takomillashtirish. Amalga oshirish muddati: 2025-yil aprel, 2025-yil may, 2025-yil may — iyul, 2026-yil dekabr, Mas’ul organ: Milliy statistika qo‘mitasi,", 
        "O‘zbekiston Respublikasi Prezidentining qarori. O‘zbekiston Respublikasi Milliy statistika qo‘mitasi faoliyatini tashkil etish chora-tadbirlari to‘g‘risida. O‘zbekiston Respublikasi Prezidentining 2025-yil 24-fevraldagi PQ-75-son qaroriga 7-ILOVA. Rasmiy statistika sohasida islohotlarni chuqurlashtirish bo‘yicha “YO‘L XARITASI”. “YO‘L XARITASI”. Yo'nalish: Ochiq ma’lumotlar portalini takomillashtirish yo‘nalishida. 34. Ochiq ma’lumotlar sohasidagi “Open Data Inventory” va “Gender Data Compass” xalqaro reytinglarda O‘zbekiston o‘rnini yaxshilash. Amalga oshirish mexanizmi: 1) Ochiq ma’lumotlar sohasidagi “Open Data Inventory” va “Gender Data Compass” xalqaro reytinglarining yangilangan baholash tizimini o‘rganish. 2) “Open Data Inventory” va “Gender Data Compass” xalqaro reytinglarining yangilangan baholash tizimi asosida Ochiq ma’lumotlar portalida va Milliy statistika qo‘mitasining “SIAT” axborot tizimida ma’lumotlarni joylashtirish. 3) Ochiq ma’lumotlar portalida va Milliy statistika qo‘mitasining “SIAT” axborot tizimida joylashtirilgan ma’lumotlarni “Open Data Inventory” va “Gender Data Compass” reytinglarini yuritadigan “Open Data Watch” xalqaro tashkilotiga taqdim etish. Amalga oshirish muddati: 2025-yil may, 2025-yil noyabr, 2025-yil dekabr. Mas’ul organ: Milliy statistika qo‘mitasi, tegishli vazirlik va idoralar"
        ]
    scores = processor.cross_encode(query, passages)
    sorted_passages = sorted(zip(passages, scores), key=lambda x: x[1], reverse=True)
    passages = [p for p, _ in sorted_passages]
    
    print(passages)
    print(scores)
